db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=thisissecret
  volumes:
    - ./data:/var/lib/postgresql/data
redis:
  image: redis
frontend:
  build: app
  command: python app.py
  links:
    - db
    - redis


