db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=thisissecret
  volumes:
    - ./data:/var/lib/postgresql/data
redis:
  image: redis
frontend:
  build: flask-by-example
  command: python app.py
  environment:
    - APP_SETTINGS=config.DevelopmentConfig
  links:
    - db
    - redis


