db:
  image: postgres
  environment:
    - POSTGRES_USER=nc-avance
    - POSTGRES_PASSWORD=zenika
redis:
  image: redis
backend:
  image: zenika/nc-avance-solution
  command: sh backend.sh
  environment:
    - POSTGRES_USER=nc-avance
    - POSTGRES_PASSWORD=zenika
    - APP_SETTINGS=config.DevelopmentConfig
  links:
    - db
    - redis
frontend:
  image: zenika/nc-avance-solution
  command: sh frontend.sh
  ports:
    - "80:5000"
  environment:
    - POSTGRES_USER=nc-avance
    - POSTGRES_PASSWORD=zenika
    - APP_SETTINGS=config.DevelopmentConfig
  links:
    - db
    - redis


